# Generated by Django 2.2.8 on 2020-10-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenues',
        ),
    ]
