# Generated by Django 2.2.8 on 2022-10-21 14:31

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeoftheyear',
            name='theme_year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), dashboard.models.max_value_current_year]),
        ),
    ]
