# Generated by Django 2.2.8 on 2021-03-04 07:18

import ckeditor_uploader.fields
import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeOfTheYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture', models.CharField(blank=True, max_length=3000, null=True)),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('theme_image', models.ImageField(max_length=10000, upload_to='themes/')),
                ('is_active', models.BooleanField(default=True)),
                ('theme_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), dashboard.models.max_value_current_year])),
            ],
        ),
    ]
