# Generated by Django 2.2.8 on 2022-12-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221021_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenues',
            options={},
        ),
    ]
