# Generated by Django 2.2.8 on 2022-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221021_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenues',
            options={},
        ),
        migrations.AddField(
            model_name='revenues',
            name='Group',
            field=models.CharField(blank=True, choices=[('God is Able', 'God is Able'), ('Winners', 'Winners'), ('Overcomers', 'Overcomers'), ('Biyinzika', 'Biyinzika'), ('Victors', 'Victors'), ('Issachar', 'Issachar')], max_length=100, null=True),
        ),
    ]
