# Generated by Django 2.2.8 on 2021-03-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210303_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Children',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Spouse',
            field=models.CharField(blank=True, default='Spouse', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=20000, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Education_Level',
            field=models.CharField(blank=True, choices=[('Masters', 'Master'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Still_Studying', 'Still_Studying'), ('Primary_Graduate', 'Primary_Graduate'), ('O_Level_Graduate', 'O_Level_Graduate'), ('A_Level_Graduate', 'A_Level_Graduate'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Home_Cell',
            field=models.CharField(blank=True, choices=[('Church Zone', 'Church Zone'), ('Kabira Zone', 'Kabira Zone'), ('Kafunda Zone', 'Kafunda Zone'), ('Lugoba Zone', 'Lugoba Zone'), ('Katooke Zone', 'Katooke Zone'), ('Kazo Zone', 'Kazo Zone'), ('Gombolola Zone', 'Gombolola Zone'), ('Kawaala Zone', 'Kawaala Zone'), ('Bombo Rd Zone', 'Bombo Rd Zone'), ('Kampala Metropolitan', 'Kampala Metropolitan')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Photo',
            field=models.ImageField(blank=True, max_length=20000, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Education_Level',
            field=models.CharField(blank=True, choices=[('Masters', 'Master'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Still_Studying', 'Still_Studying'), ('Primary_Graduate', 'Primary_Graduate'), ('O_Level_Graduate', 'O_Level_Graduate'), ('A_Level_Graduate', 'A_Level_Graduate'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='themeoftheyear',
            name='scripture',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
