# Generated by Django 2.2.8 on 2021-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210308_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Spouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
