# Generated by Django 2.2.8 on 2022-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221209_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenues',
            name='Group',
            field=models.CharField(blank=True, choices=[('God is Able', 'God is Able'), ('Winners', 'Winners'), ('Overcomers', 'Overcomers'), ('Biyinzika', 'Biyinzika'), ('Victors', 'Victors'), ('Issachar', 'Issachar')], default='God Is Able', max_length=100, null=True),
        ),
    ]
