# Generated by Django 2.2.8 on 2021-03-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210308_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='children_field_count',
        ),
        migrations.AlterField(
            model_name='members',
            name='Children',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
