# Generated by Django 2.2.8 on 2022-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_revenues_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFloat',
        ),
        migrations.AlterField(
            model_name='revenues',
            name='Group',
            field=models.CharField(blank=True, choices=[('God is Able', 'God is Able'), ('Winners', 'Winners'), ('Overcomers', 'Overcomers'), ('Biyinzika', 'Biyinzika'), ('Victors', 'Victors'), ('Issachar', 'Issachar')], max_length=100, null=True),
        ),
    ]
