# Generated by Django 2.2.8 on 2022-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20221221_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Allowances_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Bills_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Help_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Love_Offering_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Other_Expenses_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Savings_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Tithe_Of_Tithes_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
