# Generated by Django 2.2.8 on 2020-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201027_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenues',
            name='Member_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='revenues',
            name='Member_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
