# Generated by Django 2.2.8 on 2021-04-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210313_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='user@uccbwaise.org', max_length=255, null=True),
        ),
    ]
