# Generated by Django 2.2.8 on 2020-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201027_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenues',
            old_name='Electricity_Amount',
            new_name='Bills_Amount',
        ),
        migrations.AddField(
            model_name='revenues',
            name='Building_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='revenues',
            name='Love_Offering_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='revenues',
            name='Thanks_Giving_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='revenues',
            name='Service',
            field=models.CharField(blank=True, choices=[('Sunday First Service', 'Sunday First Service'), ('Sunday Second Service', 'Sunday Second Service'), ('Sunday Third Service', 'Sunday Third Service'), ('All Sunday Services', 'All Sunday Services'), ('Unspecified Service', 'Unspecified Service'), ('Home Cell Service', 'Home Cell Service'), ('Youth Service', 'Youth Service'), ('Wednesday Service', 'Wednesday Service'), ('Bible Study Service', 'Bible Study Service'), ('Friday Overnight', 'Friday Overnight')], max_length=100, null=True),
        ),
    ]
