# Generated by Django 2.2.8 on 2023-01-08 18:12

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221231_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Data_or_airtime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Lunch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Transport',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='themeoftheyear',
            name='theme_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1984), dashboard.models.max_value_current_year]),
        ),
    ]
