# Generated by Django 2.2.8 on 2021-04-27 13:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210422_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='LwakiOliMulamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('which_type', models.CharField(blank=True, choices=[('mission', 'mission'), ('conference', 'conference')], default='No', max_length=100, null=True)),
                ('preachers', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('embedded_video', models.CharField(blank=True, max_length=500, null=True)),
                ('day', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, max_length=2000000, null=True, upload_to='images/')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField()),
                ('audio_file', models.FileField(blank=True, max_length=1000000, null=True, upload_to='audios/')),
                ('conference_theme', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.AnnualConference')),
            ],
        ),
    ]
