# Generated by Django 2.2.8 on 2020-10-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201028_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenues',
            name='Envag_Or_Missions_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
