# Generated by Django 2.2.8 on 2023-01-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230108_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Seed_Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Main_Expense_Reason',
            field=models.CharField(blank=True, choices=[('Water Bills', 'Water Bills'), ('Yaka Bills', 'Yaka Bills'), ('Transport', 'Transport'), ('Love Offering', 'Love Offering'), ('Medical Bills', 'Medical Bills'), ('Rent', 'Rent'), ('Help', 'Help'), ('Savings', 'Savings'), ('Evangelism', 'Evangelism'), ('Tithe of Tithes', 'Tithe of Tithes'), ('Generator Mechanic', 'Generator Mechanic'), ('Instruments', 'Servicing Music Instruments'), ('Condolences', 'Condolences'), ('Stationery', 'Stationery'), ('Repair', 'Any Other Repair'), ('Renovations', 'Renovations')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Petty_Cash_Reason',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Breakfast', 'Breakfast'), ('Upkeep', 'Upkeep'), ('Airtime or Data', 'Airtime or Data'), ('Other', 'Other')], max_length=1000, null=True),
        ),
    ]
