# Generated by Django 2.2.8 on 2020-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(null=True, upload_to='about/')),
                ('about', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
