# Generated by Django 2.2.8 on 2021-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_lwakiolimulamu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwakiolimulamu',
            name='topic_or_sub_title',
            field=models.CharField(blank=True, default='Topic or sub title', max_length=5000, null=True),
        ),
    ]
