# Generated by Django 2.2.8 on 2021-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210419_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualconference',
            name='audio_file',
            field=models.FileField(blank=True, max_length=1000000, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='annualconference',
            name='embedded_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='annualconference',
            name='image',
            field=models.ImageField(blank=True, max_length=2000000, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='annualconference',
            name='preacher',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
