# Generated by Django 2.2.8 on 2020-02-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=300)),
                ('Is_View_on_Web', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_location', models.CharField(choices=[('Header', 'Header'), ('Footer', 'Footer')], default='Header', max_length=100)),
                ('page_title', models.CharField(max_length=100)),
                ('page_description', models.TextField(max_length=300)),
                ('page_image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(null=True, upload_to='images/')),
                ('image_caption', models.CharField(max_length=100)),
                ('gallery_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Gallery')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
