# Generated by Django 2.2.8 on 2023-01-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20230114_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Renovation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Stationery',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
