# Generated by Django 2.2.8 on 2020-10-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_revenues_envag_or_missions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfloat',
            name='TopUpAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
