# Generated by Django 2.2.8 on 2023-01-08 21:30

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20221223_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Data_or_airtime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Lunch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Transport',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Main_Expense_Reason',
            field=models.CharField(blank=True, choices=[('Water Bills', 'Water Bills'), ('Yaka Bills', 'Yaka Bills'), ('Transport', 'Transport'), ('Love Offering', 'Love Offering'), ('Medical Bills', 'Medical Bills'), ('Rent', 'Rent'), ('Help', 'Help'), ('Savings', 'Savings'), ('Evangelism', 'Evangelism'), ('Tithe of Tithes', 'Tithe of Tithes'), ('Generator Mechanic', 'Generator Mechanic'), ('Instruments', 'Servicing Music Instruments'), ('Condolences', 'Condolences'), ('Stationery', 'Stationery'), ('Repair', 'Any Other Repair'), ('Renovations', 'Renovations')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='themeoftheyear',
            name='theme_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1984), dashboard.models.max_value_current_year]),
        ),
    ]
