# Generated by Django 2.2.8 on 2020-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_cashfloat_topupamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfloat',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
