# Generated by Django 2.2.8 on 2021-04-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210427_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualconference',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='annualconference',
            name='embedded_video',
        ),
        migrations.RemoveField(
            model_name='annualconference',
            name='image',
        ),
        migrations.RemoveField(
            model_name='annualconference',
            name='preacher',
        ),
        migrations.CreateModel(
            name='LwakiOliMulamu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('preacher', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('embedded_video', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, max_length=2000000, null=True, upload_to='images/')),
                ('audio_file', models.FileField(blank=True, max_length=1000000, null=True, upload_to='audios/')),
                ('conference_theme', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.AnnualConference')),
            ],
        ),
    ]
