# Generated by Django 2.2.8 on 2021-05-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210501_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_full_name',
            field=models.CharField(blank=True, default='ucc bwaise', max_length=300, null=True),
        ),
    ]
