# Generated by Django 2.2.8 on 2021-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210427_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwakiolimulamu',
            name='which_type',
            field=models.CharField(blank=True, choices=[('mission', 'mission'), ('conference', 'conference')], default='No', max_length=100, null=True),
        ),
    ]
