# Generated by Django 2.2.8 on 2021-04-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_lwakiolimulamu_which_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwakiolimulamu',
            name='day',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
