# Generated by Django 2.2.8 on 2021-04-27 13:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_lwakiolimulamu_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lwakiolimulamu',
            old_name='preacher',
            new_name='preachers',
        ),
        migrations.AddField(
            model_name='lwakiolimulamu',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='testing'),
            preserve_default=False,
        ),
    ]
