# Generated by Django 2.2.8 on 2020-02-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200205_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_code', models.CharField(blank=True, max_length=130, null=True)),
                ('church_name', models.CharField(max_length=130)),
                ('address', models.CharField(max_length=130)),
                ('phone', models.CharField(max_length=130)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('email_address', models.EmailField(max_length=120)),
                ('fax', models.CharField(blank=True, max_length=130, null=True)),
                ('footer', models.CharField(blank=True, max_length=130, null=True)),
                ('enable_frontend', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=130)),
                ('latitude', models.CharField(blank=True, max_length=130, null=True)),
                ('longitude', models.CharField(blank=True, max_length=130, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=130, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=130, null=True)),
                ('linkedIn_url', models.URLField(blank=True, max_length=130, null=True)),
                ('google_plus_url', models.URLField(blank=True, max_length=130, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=130, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=130, null=True)),
                ('pinterest_url', models.URLField(blank=True, max_length=130, null=True)),
                ('frontend_Logo', models.ImageField(upload_to='logo/')),
                ('backend_Logo', models.ImageField(upload_to='logo/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=130, null=True)),
            ],
            options={
                'verbose_name': 'church',
                'verbose_name_plural': 'churches',
                'ordering': ('church_name',),
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
