# Generated by Django 2.2.8 on 2020-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Is_View_on_Web',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True),
        ),
    ]
