# Generated by Django 2.2.8 on 2020-02-06 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_image_is_view_on_web'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
