# Generated by Django 2.2.8 on 2020-02-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200206_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='maps_embedded_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
