# Generated by Django 2.2.8 on 2020-02-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_church_maps_embedded_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=130, null=True)),
                ('phone', models.CharField(max_length=130)),
                ('subject', models.CharField(max_length=130)),
                ('message', models.TextField(max_length=130)),
            ],
        ),
    ]
