# Generated by Django 2.2.8 on 2021-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
