# Generated by Django 2.2.8 on 2020-02-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200207_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='feedback',
            field=models.TextField(blank=True, max_length=130, null=True),
        ),
    ]
