# Generated by Django 2.2.8 on 2020-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_contact_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='feedback',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
