# Generated by Django 2.2.8 on 2020-02-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200213_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='fax',
            new_name='Post_Office_Box',
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.CharField(default='vision', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='church_mission',
            field=models.CharField(default='mission', max_length=1000),
        ),
        migrations.AddField(
            model_name='church',
            name='church_vision',
            field=models.CharField(default='vision', max_length=1000),
        ),
    ]
