# Generated by Django 2.2.8 on 2020-02-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200213_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='vision',
            new_name='mission_description',
        ),
        migrations.AddField(
            model_name='about',
            name='Is_View_on_Web',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_description',
            field=models.CharField(default='vision', max_length=100),
            preserve_default=False,
        ),
    ]
