# Generated by Django 2.2.8 on 2020-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20200213_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_description',
            field=models.TextField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision_description',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
    ]
