# Generated by Django 2.2.8 on 2020-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_about_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, default='Preacher', max_length=1003, null=True),
        ),
    ]
