# Generated by Django 2.2.8 on 2020-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20200213_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Ministry_Involved_In',
            field=models.CharField(blank=True, choices=[('Pastoral', 'Pastoral'), ('Discipleship', 'Discipleship'), ('Worship Team', 'Worship Team'), ('Ushering', 'Ushering'), ('Orchestra', 'Orchestra'), ('Youth Leadership', 'Youth Leadership'), ('Teens', 'Teens')], default='Discipleship', max_length=100, null=True),
        ),
    ]
