# Generated by Django 2.2.8 on 2020-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20200213_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_View_on_Web',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_for',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Members', 'Members'), ('Secretary', 'Secretary'), ('Admin', 'Admin'), ('Building Chair', 'Building Chair'), ('Marrieds Leader', 'Marrieds Leader'), ('Youth Leader', 'Youth Leader')], max_length=20, null=True),
        ),
    ]
