# Generated by Django 2.2.8 on 2020-02-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20200213_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Secretary', 'Secretary'), ('SuperAdmin', 'SuperAdmin'), ('Building Chair', 'Building Chair'), ('Marrieds Leader', 'Marrieds Leader'), ('Youth Leader', 'Youth Leader')], max_length=250),
        ),
    ]
