# Generated by Django 2.1.7 on 2019-08-21 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20190426_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledges',
            name='Contact_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 346314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 345316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offeringsreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 348280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 346314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 348280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 344291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 347333, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 346314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 345316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 347333, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 345316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 20, 1, 42, 348280, tzinfo=utc)),
        ),
    ]
