# Generated by Django 2.2.8 on 2020-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20200213_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='More_Info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
