# Generated by Django 2.2.4 on 2019-11-29 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20190821_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 107348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 104386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offeringsreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 109377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 105411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 111335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 102391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 108419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 106381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 103419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 108419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 104386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 15, 30, 2, 110338, tzinfo=utc)),
        ),
    ]
