# Generated by Django 2.2.8 on 2020-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_members_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='More_Info',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
