# Generated by Django 2.2.4 on 2019-12-10 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20191129_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledges',
            old_name='AmountInWords',
            new_name='Amount_In_Words',
        ),
        migrations.RenameField(
            model_name='pledges',
            old_name='DayOfTheWeek',
            new_name='Day_Of_The_Week',
        ),
        migrations.RenameField(
            model_name='pledges',
            old_name='PledgeMadeBy',
            new_name='Pledge_Made_By',
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 266159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 262175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offeringsreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 269083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 263135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 270113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 260148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 268149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 264162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 261142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 267121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 262175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 18, 7, 34, 269083, tzinfo=utc)),
        ),
    ]
