# Generated by Django 2.2.8 on 2020-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20200214_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='tithesreportarchive',
            name='Service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
