# Generated by Django 2.2.8 on 2020-02-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_tithesreportarchive_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Service',
            field=models.CharField(blank=True, default='Third Service', max_length=100, null=True),
        ),
    ]
