# Generated by Django 2.2.8 on 2020-02-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20200215_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidpledges',
            name='Pledge_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
