# Generated by Django 2.2.4 on 2019-12-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20191211_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledges',
            name='Contact_Number',
        ),
    ]
