# Generated by Django 2.2.4 on 2019-12-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_pledges_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidPledges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Member_id', models.CharField(max_length=100)),
                ('Amount_Paid', models.IntegerField(blank=True, default=0, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
