# Generated by Django 2.2.8 on 2020-02-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20200217_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Secretary', 'Secretary'), ('SuperAdmin', 'SuperAdmin'), ('Building Chair', 'Building Chair'), ('Marrieds Leader', 'Marrieds Leader'), ('Youth Leader', 'Youth Leader'), ('Ordinary', 'Ordinary')], max_length=250),
        ),
    ]
