# Generated by Django 2.2.8 on 2020-01-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_paidpledges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgesreportarchive',
            old_name='Amount',
            new_name='Amount_Paid',
        ),
        migrations.RemoveField(
            model_name='paidpledges',
            name='Member_id',
        ),
        migrations.RemoveField(
            model_name='paidpledges',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='pledgesreportarchive',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='pledgesreportarchive',
            name='Name',
        ),
        migrations.AddField(
            model_name='paidpledges',
            name='Pledge_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paidpledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(default='1', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledges',
            name='Status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pledgesreportarchive',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pledgesreportarchive',
            name='Pledge_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledgesreportarchive',
            name='Pledge_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AddField(
            model_name='pledgesreportarchive',
            name='Pledged_Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pledgesreportarchive',
            name='Status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
