# Generated by Django 2.2.8 on 2020-01-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20200106_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerings',
            old_name='TotalOffering',
            new_name='Total_Offering',
        ),
    ]
