# Generated by Django 2.2.8 on 2020-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20200218_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrenovation',
            name='Archived_Status',
            field=models.CharField(blank=True, choices=[('Archived', 'Archived'), ('UnArchived', 'UnArchived')], default='Archived', max_length=100, null=True),
        ),
    ]
