# Generated by Django 2.2.8 on 2020-01-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20200106_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerings',
            name='Service',
            field=models.CharField(choices=[('Home Cell', 'Home Cell'), ('Youth Service', 'Youth Service'), ('Wednesday Service', 'Wednesday Servuce'), ('Bible Study', 'Bible Study'), ('Friday Overnight', 'Friday Overnight'), ('First Service', 'First Service'), ('Secon Service', 'Second Service'), ('Third Service', 'Third Service')], default='Service', max_length=100),
            preserve_default=False,
        ),
    ]
