# Generated by Django 2.2.8 on 2020-01-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_offerings_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeringsreportarchive',
            old_name='Day',
            new_name='Service',
        ),
    ]
