# Generated by Django 2.2.8 on 2020-01-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20200106_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='PaymentMadeTo',
            new_name='Payment_Made_To',
        ),
        migrations.RenameField(
            model_name='spend',
            old_name='ReasonForPayment',
            new_name='Reason_For_Payment',
        ),
        migrations.RenameField(
            model_name='sundry',
            old_name='PaymentMadeTo',
            new_name='Payment_Made_To',
        ),
        migrations.RenameField(
            model_name='sundry',
            old_name='ReasonForPayment',
            new_name='Reason_For_Payment',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='AmountInWords',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='AmountInWords',
        ),
        migrations.RemoveField(
            model_name='sundry',
            name='AmountInWords',
        ),
        migrations.AlterField(
            model_name='salary',
            name='Name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
    ]
