# Generated by Django 2.2.8 on 2020-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20200218_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrenovation',
            name='archivedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingrenovation',
            name='archivedService',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buildingrenovation',
            name='archivedTotal_Collection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
