# Generated by Django 2.2.8 on 2020-01-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20200106_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='Address',
            new_name='Residence',
        ),
        migrations.AddField(
            model_name='members',
            name='Home_Cell',
            field=models.CharField(choices=[('Church Zone', 'Church Zone'), ('Kabira Zone', 'Kabira Zone'), ('Kafunda Zone', 'Kafunda Zone'), ('Lugoba Zone', 'Lugoba Zone'), ('Katooke Zone', 'Katooke Zone'), ('Kazo Zone', 'Kazo Zone'), ('Gombolola Zone', 'Gombolola Zone'), ('Kawaala Zone', 'Kawaala Zone'), ('Bombo Rd Zone', 'Bombo Rd Zone')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Photo',
            field=models.ImageField(default='home', upload_to='avatars/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spend',
            name='Reason_For_Payment',
            field=models.CharField(choices=[('Church Renovations', 'Church Renovations'), ('Water Bills', 'Water Bills'), ('Electricity', 'Electricity Bills'), ('Lwaki Oli Mulamu Conference', 'Lwaki Oli Mulamu Conference')], max_length=100),
        ),
    ]
