# Generated by Django 2.2.8 on 2020-02-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20200218_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingrenovation',
            name='archivedDate',
        ),
        migrations.RemoveField(
            model_name='buildingrenovation',
            name='archivedService',
        ),
        migrations.RemoveField(
            model_name='buildingrenovation',
            name='archivedTotal_Collection',
        ),
    ]
