# Generated by Django 2.2.8 on 2020-01-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20200106_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salary',
            new_name='Allowance',
        ),
        migrations.RenameModel(
            old_name='SalaryReportArchive',
            new_name='AllowanceReportArchive',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='Duties',
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='image',
            field=models.ImageField(default='Photo', upload_to='avatars/'),
        ),
    ]
