# Generated by Django 2.2.8 on 2020-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20200218_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingrenovation',
            name='Archived_Status',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('NOT-ARCHIVED', 'NOT-ARCHIVED')], default='NOT-ARCHIVED', max_length=100, null=True),
        ),
    ]
