# Generated by Django 2.2.8 on 2020-02-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20200218_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingrenovation',
            name='archivedmonth',
        ),
        migrations.RemoveField(
            model_name='buildingrenovation',
            name='archivedyear',
        ),
    ]
