# Generated by Django 2.2.8 on 2020-01-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20200109_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='Salary',
            new_name='Salary_Amount',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='FistName',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='SecondName',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Date_of_employment',
            field=models.DateField(default='2019-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='End_of_contract',
            field=models.DateField(default='2019-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Role',
            field=models.CharField(default='duty', max_length=20),
        ),
    ]
