# Generated by Django 2.2.8 on 2020-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20200218_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Payment_Made_To', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Main_Expense_Reason', models.CharField(blank=True, choices=[('Water Bills', 'Water Bills'), ('Yaka Bills', 'Yaka Bills'), ('Transport', 'Transport'), ('Love Offering', 'Love Offering'), ('Medical Bills', 'Medical Bills'), ('Rent', 'Rent'), ('Help', 'Help'), ('Drinks', 'Drinks'), ('Savings', 'Savings'), ('Evangelism', 'Evangelism')], max_length=100, null=True)),
                ('General_Expenses_Reason', models.CharField(blank=True, choices=[('Generator Mechanic', 'Generator Mechanic'), ('Instruments', 'Servicing Music Instruments'), ('Condolences', 'Condolences'), ('Stationery', 'Stationery'), ('Repair', 'Any Other Repair'), ('Purchase', 'Purchase'), ('Renovations', 'Renovations')], max_length=100, null=True)),
                ('Petty_Cash_Reason', models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Upkeep', 'Upkeep'), ('Airtime/Data', 'Airtime/Data')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GeneralExpenses',
        ),
        migrations.DeleteModel(
            name='Spend',
        ),
        migrations.DeleteModel(
            name='Sundry',
        ),
    ]
