# Generated by Django 2.2.8 on 2020-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20200109_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='Role',
            field=models.CharField(max_length=200),
        ),
    ]
