# Generated by Django 2.2.8 on 2020-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20200109_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='Date',
            field=models.DateField(default='2019-10-10'),
            preserve_default=False,
        ),
    ]
