# Generated by Django 2.2.8 on 2020-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20200219_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Archived_Status',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('NOT-ARCHIVED', 'NOT-ARCHIVED')], default='NOT-ARCHIVED', max_length=100, null=True),
        ),
    ]
