# Generated by Django 2.2.8 on 2020-01-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_staffdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalariesPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=200, null=True)),
                ('Salary_Amount', models.IntegerField(default=0)),
                ('Name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members')),
            ],
        ),
    ]
