# Generated by Django 2.2.8 on 2020-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_auto_20200109_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='salariespaid',
            name='Salary_Id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
