# Generated by Django 2.2.8 on 2020-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20200219_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenues',
            name='Other_Sources',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
