# Generated by Django 2.2.8 on 2020-01-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_salariespaid_salary_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='Date',
            new_name='Date_of_paying_salary',
        ),
        migrations.RemoveField(
            model_name='salariespaid',
            name='Date',
        ),
        migrations.AddField(
            model_name='salariespaid',
            name='Date_of_paying_salary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salariespaid',
            name='Month_being_cleared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Month_being_cleared',
            field=models.DateField(blank=True, null=True),
        ),
    ]
