# Generated by Django 2.2.8 on 2020-01-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20200109_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='Name',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Date_Of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Education_Level',
            field=models.CharField(choices=[('Masters', 'Master'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Faith',
            field=models.CharField(choices=[('Born Again', 'Born Again'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Photo',
            field=models.ImageField(default='testing', upload_to='avatars/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Residence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Second_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='Telephone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitors',
            name='Photo',
            field=models.ImageField(default='testing', upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
