# Generated by Django 2.2.8 on 2020-02-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_revenues_other_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Other_Expenditure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Petty_Cash_Reason',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Upkeep', 'Upkeep'), ('Airtime/Data', 'Airtime/Data'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
