# Generated by Django 2.2.8 on 2020-02-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20200220_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Member_Name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
    ]
