# Generated by Django 2.2.8 on 2020-01-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20200109_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='Role',
            field=models.CharField(blank=True, choices=[('Security', 'Security'), ('Secretary', 'Secretary'), ('Church-Welfare', 'Church-Welfare')], max_length=200, null=True),
        ),
    ]
