# Generated by Django 2.2.8 on 2020-01-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_auto_20200109_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salariespaid',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
