# Generated by Django 2.2.8 on 2020-02-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_expenditures_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditures',
            name='Payment_Made_To',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
