# Generated by Django 2.2.8 on 2020-01-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_tithes_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidpledges',
            name='Reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
