# Generated by Django 2.2.8 on 2020-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20200221_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingRenovation',
        ),
        migrations.AddField(
            model_name='revenues',
            name='Other_Notes',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
