# Generated by Django 2.2.8 on 2020-01-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_salariespaidreportarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_That_Needs_Pledges', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount_Needed', models.IntegerField(blank=True, default=0, null=True)),
                ('Pledge_Deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
