# Generated by Django 2.2.8 on 2020-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_pledgeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgeitem',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
