# Generated by Django 2.2.8 on 2020-02-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20200221_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenues',
            options={'ordering': ['-Date']},
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revenues',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
