# Generated by Django 2.2.8 on 2020-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20200221_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Archived_Status',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('NOT-ARCHIVED', 'NOT-ARCHIVED')], default='NOT-ARCHIVED', max_length=100, null=True),
        ),
    ]
