# Generated by Django 2.2.8 on 2020-01-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_auto_20200113_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundry',
            name='Reason_For_Payment',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Upkeep', 'Upkeep')], max_length=250),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
