# Generated by Django 2.2.8 on 2020-03-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_pledges_archived_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledges',
            name='Pledge_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
