# Generated by Django 2.2.8 on 2020-01-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20200113_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Payment_Made_To', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Expense_Reason', models.CharField(choices=[('GM', 'Generator Mechanic'), ('Instruments', 'Servicing Music Instruments'), ('Condolences', 'Condolences'), ('Stationery', 'Stationery'), ('Repair', 'Any Other Repair'), ('Purchase', 'Purchase'), ('Renovations', 'Renovations')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='spend',
            name='Reason_For_Payment',
            field=models.CharField(choices=[('Water Bills', 'Water Bills'), ('YB', 'Yaka Bills'), ('Transport', 'Transport'), ('LO', 'Love Offering'), ('MB', 'Medical Bills'), ('Rent', 'Rent'), ('Help', 'Help'), ('Drinks', 'Drinks'), ('Savings', 'Savings'), ('Evangelism', 'Evangelism')], max_length=100),
        ),
    ]
