# Generated by Django 2.2.8 on 2020-03-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_pledges_pledge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='Amount_Paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
