# Generated by Django 2.2.8 on 2020-01-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20200113_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralExpensesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Name', models.CharField(default='Name', max_length=100, null=True)),
                ('Amount', models.FloatField(default=0.0, null=True)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
