# Generated by Django 2.2.8 on 2020-03-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20200303_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='Amount_Pledged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
