# Generated by Django 2.2.8 on 2020-01-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_generalexpensesreportarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexpenses',
            name='Expense_Reason',
            field=models.CharField(choices=[('Generator Mechanic', 'Generator Mechanic'), ('Instruments', 'Servicing Music Instruments'), ('Condolences', 'Condolences'), ('Stationery', 'Stationery'), ('Repair', 'Any Other Repair'), ('Purchase', 'Purchase'), ('Renovations', 'Renovations')], max_length=100),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Reason_For_Payment',
            field=models.CharField(choices=[('Water Bills', 'Water Bills'), ('Yaka Bills', 'Yaka Bills'), ('Transport', 'Transport'), ('Love Offering', 'Love Offering'), ('Medical Bills', 'Medical Bills'), ('Rent', 'Rent'), ('Help', 'Help'), ('Drinks', 'Drinks'), ('Savings', 'Savings'), ('Evangelism', 'Evangelism')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Reason_For_Payment',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Upkeep', 'Upkeep'), ('Airtime/Data', 'Airtime/Data')], max_length=250),
        ),
    ]
