# Generated by Django 2.2.8 on 2020-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_auto_20200303_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgeitem',
            name='Archived_Status',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('NOT-ARCHIVED', 'NOT-ARCHIVED')], default='NOT-ARCHIVED', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PledgesReportArchive',
        ),
    ]
