# Generated by Django 2.2.8 on 2020-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_auto_20200117_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Contact_Of_Next_Of_Kin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='County',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Date_Of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Date_Of_Joining_UCC_Bwaise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Date_Of_Salvation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='District',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Education_Level',
            field=models.CharField(blank=True, choices=[('Masters', 'Master'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('None', 'None'), ('Still_Studying', 'Still_Studying'), ('Primary_Graduate', 'Primary_Graduate'), ('O_Level_Graduate', 'O_Level_Graduate'), ('A_Level_Graduate', 'A_Level_Graduate')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widower', 'Widower'), ('Widow', 'Widow')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Marriage_Kind',
            field=models.CharField(blank=True, choices=[('Church_Marriage', 'Church_Marriage'), ('Customary', 'Customary'), ('Legal', 'Legal'), ('Cohabiting', 'Cohabiting')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Ministry_Involved_In',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Name_Of_Next_Of_Kin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Parish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Place_of_Work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Profession',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Residence_Of_Next_Of_Kin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Sub_County',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Type_of_Work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
