# Generated by Django 2.2.8 on 2020-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_cashfloat'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditures',
            name='Employee_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenditures',
            name='Salary_Id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
