# Generated by Django 2.2.8 on 2020-03-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_auto_20200309_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditures',
            name='Employee_Name',
        ),
        migrations.RemoveField(
            model_name='expenditures',
            name='Salary_Id',
        ),
    ]
