# Generated by Django 2.2.8 on 2020-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_seedsreportarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Donated_By', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('Reason', models.CharField(max_length=100)),
            ],
        ),
    ]
