# Generated by Django 2.2.8 on 2020-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationsReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Reason', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
