# Generated by Django 2.2.8 on 2020-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_auto_20200309_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_for',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Members', 'Members'), ('Secretary', 'Secretary'), ('Admin', 'Admin'), ('Assistant_Admin', 'Assistant_Admin'), ('Building Chair', 'Building Chair'), ('Marrieds Leader', 'Marrieds Leader'), ('Youth Leader', 'Youth Leader')], max_length=20, null=True),
        ),
    ]
