# Generated by Django 2.2.8 on 2020-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_auto_20200427_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_for',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Members', 'Members'), ('Secretary', 'Secretary'), ('Admin', 'Admin'), ('Building Chair', 'Building Chair'), ('Marrieds Leader', 'Marrieds Leader'), ('Youth Leader', 'Youth Leader')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Secretary', 'Secretary'), ('SuperAdmin', 'SuperAdmin'), ('Building Chair', 'Building Chair'), ('Marrieds Leader', 'Marrieds Leader'), ('Youth Leader', 'Youth Leader'), ('Ordinary', 'Ordinary'), ('Assistant_Admin', 'Assistant_Admin'), ('Website Admin', 'Website Admin')], max_length=250, null=True),
        ),
    ]
