# Generated by Django 2.2.8 on 2020-01-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_donationsreportarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='Name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='paidpledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Reason',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.PledgeItem'),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Pledge_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='Seed_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='seedsreportarchive',
            name='Seed_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Tithe_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Tithe_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.CreateModel(
            name='ThanksGivingReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('Service', models.CharField(max_length=100, null=True)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
                ('Thanks_Giving_By', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members')),
            ],
        ),
        migrations.CreateModel(
            name='ThanksGiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('Service', models.CharField(choices=[('Home Cell Service', 'Home Cell Service'), ('Youth Service', 'Youth Service'), ('Wednesday Service', 'Wednesday Service'), ('Bible Study Service', 'Bible Study Service'), ('Friday Overnight', 'Friday Overnight'), ('SundayFirst Service', 'Sunday First Service'), ('Sunday Second Service', 'Sunday Second Service'), ('Sunday Third Service', 'Sunday Third Service')], max_length=100)),
                ('Thanks_Giving_By', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members')),
            ],
        ),
    ]
