# Generated by Django 3.0.5 on 2020-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='Is_View_on_Web',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True),
        ),
    ]
