# Generated by Django 2.2.8 on 2020-01-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_auto_20200124_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
