# Generated by Django 3.0.6 on 2020-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_members_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('project_description', models.TextField()),
                ('Is_View_on_Web', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.AlterField(
            model_name='revenues',
            name='Service',
            field=models.CharField(blank=True, choices=[('Unspecified Service', 'Unspecified Service'), ('Home Cell Service', 'Home Cell Service'), ('Youth Service', 'Youth Service'), ('Wednesday Service', 'Wednesday Service'), ('Bible Study Service', 'Bible Study Service'), ('Friday Overnight', 'Friday Overnight'), ('Sunday First Service', 'Sunday First Service'), ('Sunday Second Service', 'Sunday Second Service'), ('Sunday Third Service', 'Sunday Third Service')], max_length=100, null=True),
        ),
    ]
