# Generated by Django 3.0.6 on 2020-05-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_auto_20200530_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
    ]
