# Generated by Django 3.0.6 on 2020-05-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_project_project_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('colour', models.CharField(max_length=40)),
                ('theme_image', models.ImageField(null=True, upload_to='theme/')),
                ('is_active', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
