# Generated by Django 2.2.8 on 2020-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20200124_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Secretary', 'Secretary')], default='Admin', max_length=250),
            preserve_default=False,
        ),
    ]
