# Generated by Django 2.2.8 on 2020-05-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='theme_image',
        ),
    ]
