# Generated by Django 2.2.8 on 2020-01-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
