# Generated by Django 2.2.8 on 2020-06-03 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_remove_theme_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='Education_Level',
            field=models.CharField(blank=True, choices=[('Masters', 'Masters'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Education_Level',
            field=models.CharField(blank=True, choices=[('Masters', 'Masters'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=100, null=True),
        ),
    ]
