# Generated by Django 2.2.8 on 2020-01-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='Church_Member',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Members'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='UCC_Bwaise_Member',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='First_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Second_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
