# Generated by Django 2.2.8 on 2020-01-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_auto_20200124_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='Education_Level',
            field=models.CharField(blank=True, choices=[('Masters', 'Master'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Faith',
            field=models.CharField(blank=True, choices=[('Born Again', 'Born Again'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
