# Generated by Django 2.2.8 on 2020-01-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_auto_20200125_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
