# Generated by Django 2.2.8 on 2020-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_auto_20200125_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='Role',
            field=models.CharField(blank=True, choices=[('Security', 'Security'), ('Secretary', 'Secretary'), ('Church-Welfare', 'Church-Welfare'), ('Admin', 'Admin')], max_length=200, null=True),
        ),
    ]
