# Generated by Django 2.2.8 on 2020-06-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_auto_20200603_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
