# Generated by Django 2.2.8 on 2020-01-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0090_auto_20200125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Secretary', 'Secretary'), ('SuperAdmin', 'SuperAdmin')], max_length=250),
        ),
    ]
