# Generated by Django 2.2.8 on 2020-01-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_auto_20200126_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='Name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='paidpledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Reason',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.PledgeItem'),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Pledge_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='Seed_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='seedsreportarchive',
            name='Seed_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Church_Member',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='thanksgiving',
            name='Thanks_Giving_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='thanksgivingreportarchive',
            name='Thanks_Giving_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Tithe_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Tithe_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
    ]
