# Generated by Django 2.2.8 on 2020-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_auto_20200607_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='is_church_member',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=100),
            preserve_default=False,
        ),
    ]
