# Generated by Django 2.2.8 on 2020-01-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_auto_20200126_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidpledges',
            name='Reason',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.PledgeItem'),
        ),
    ]
