# Generated by Django 2.2.8 on 2020-06-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_auto_20200607_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Pledge_Made_By_Visitor',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Visitors'),
        ),
    ]
