# Generated by Django 2.2.8 on 2020-01-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_auto_20200126_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgesCashedOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Item_That_Needs_Pledges', models.CharField(blank=True, max_length=100, null=True)),
                ('Item_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount_Needed', models.IntegerField(blank=True, default=0, null=True)),
                ('Amount_Cashed_Out', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
