# Generated by Django 2.2.8 on 2020-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_auto_20200607_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='is_church_member',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=100, null=True),
        ),
    ]
