# Generated by Django 2.2.8 on 2020-06-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_auto_20200607_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaidPledges',
        ),
    ]
