# Generated by Django 2.2.8 on 2020-06-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_delete_paidpledges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='photos',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Date_of_employment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='End_of_contract',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
