# Generated by Django 2.2.8 on 2020-01-28 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_auto_20200128_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='Name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='paidpledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='paidpledges',
            name='Reason',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PledgeItem'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Reason',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PledgeItem'),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Pledge_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='Seed_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='seedsreportarchive',
            name='Seed_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Church_Member',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='thanksgiving',
            name='Thanks_Giving_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='thanksgivingreportarchive',
            name='Thanks_Giving_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Tithe_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Tithe_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Post_content', models.TextField()),
                ('Date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
