# Generated by Django 2.2.8 on 2020-06-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_auto_20200608_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditures',
            name='Amount',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Archived_Status',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('NOT-ARCHIVED', 'NOT-ARCHIVED')], default='NOT-ARCHIVED', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='General_Expenses_Reason',
            field=models.CharField(blank=True, choices=[('Generator Mechanic', 'Generator Mechanic'), ('Instruments', 'Servicing Music Instruments'), ('Condolences', 'Condolences'), ('Stationery', 'Stationery'), ('Repair', 'Any Other Repair'), ('Purchase', 'Purchase'), ('Renovations', 'Renovations')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Main_Expense_Reason',
            field=models.CharField(blank=True, choices=[('Water Bills', 'Water Bills'), ('Yaka Bills', 'Yaka Bills'), ('Transport', 'Transport'), ('Love Offering', 'Love Offering'), ('Medical Bills', 'Medical Bills'), ('Rent', 'Rent'), ('Help', 'Help'), ('Drinks', 'Drinks'), ('Savings', 'Savings'), ('Evangelism', 'Evangelism')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Member_Name',
            field=models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Other_Expenditure',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Payment_Made_To',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Petty_Cash_Reason',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Upkeep', 'Upkeep'), ('Airtime/Data', 'Airtime/Data'), ('Other', 'Other')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='Reason_filtering',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
