# Generated by Django 2.2.8 on 2020-01-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_auto_20200128_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
    ]
