# Generated by Django 2.2.8 on 2020-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_auto_20200608_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditures',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
