# Generated by Django 2.2.8 on 2020-06-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_auto_20200608_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenditures',
        ),
    ]
