# Generated by Django 2.2.8 on 2020-02-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexpenses',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
