# Generated by Django 2.2.8 on 2020-06-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_delete_expenditures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Payment_Made_To', models.CharField(blank=True, max_length=1000, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('Reason_filtering', models.CharField(blank=True, max_length=1000, null=True)),
                ('Other_Expenditure', models.CharField(blank=True, max_length=1000, null=True)),
                ('Notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('Main_Expense_Reason', models.CharField(blank=True, choices=[('Water Bills', 'Water Bills'), ('Yaka Bills', 'Yaka Bills'), ('Transport', 'Transport'), ('Love Offering', 'Love Offering'), ('Medical Bills', 'Medical Bills'), ('Rent', 'Rent'), ('Help', 'Help'), ('Drinks', 'Drinks'), ('Savings', 'Savings'), ('Evangelism', 'Evangelism')], max_length=1000, null=True)),
                ('General_Expenses_Reason', models.CharField(blank=True, choices=[('Generator Mechanic', 'Generator Mechanic'), ('Instruments', 'Servicing Music Instruments'), ('Condolences', 'Condolences'), ('Stationery', 'Stationery'), ('Repair', 'Any Other Repair'), ('Purchase', 'Purchase'), ('Renovations', 'Renovations')], max_length=1000, null=True)),
                ('Petty_Cash_Reason', models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Upkeep', 'Upkeep'), ('Airtime/Data', 'Airtime/Data'), ('Other', 'Other')], max_length=1000, null=True)),
                ('Archived_Status', models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('NOT-ARCHIVED', 'NOT-ARCHIVED')], default='NOT-ARCHIVED', max_length=1000, null=True)),
                ('Member_Name', models.ForeignKey(blank=True, max_length=1000, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Members')),
            ],
        ),
    ]
