# Generated by Django 2.2.8 on 2020-06-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_expenditures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
