# Generated by Django 2.2.8 on 2020-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_auto_20200201_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allowancereportarchive',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donations',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donationsreportarchive',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='generalexpensesreportarchive',
            name='Amount',
            field=models.FloatField(null=True, verbose_name=0.0),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='Total_Offering',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offeringsreportarchive',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paidpledges',
            name='Amount_Paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledgeitem',
            name='Amount_Needed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Amount_Paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Amount_Pledged',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledgescashedout',
            name='Amount_Cashed_Out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledgescashedout',
            name='Amount_Needed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Amount_Paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Pledged_Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salariespaid',
            name='Salary_Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salariespaidreportarchive',
            name='Salary_Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seedsreportarchive',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Salary_Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Amount',
            field=models.FloatField(null=True, verbose_name=0.0),
        ),
        migrations.AlterField(
            model_name='thanksgiving',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thanksgivingreportarchive',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Amount',
            field=models.IntegerField(),
        ),
    ]
