# Generated by Django 2.2.8 on 2020-02-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0102_auto_20200201_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Amount_Paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Pledged_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
