# Generated by Django 2.2.8 on 2020-02-01 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_auto_20200201_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgescashedout',
            name='Item_That_Needs_Pledges',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PledgeItem'),
        ),
    ]
