# Generated by Django 2.2.8 on 2020-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0105_auto_20200610_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
