# Generated by Django 2.2.8 on 2020-06-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0106_auto_20200611_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='backend_Logo',
            new_name='Church_Logo',
        ),
        migrations.RemoveField(
            model_name='church',
            name='frontend_Logo',
        ),
    ]
