# Generated by Django 2.2.8 on 2020-07-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0107_auto_20200616_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='Pledge_Made_By',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Pledge_Made_By_Visitor',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Visitors'),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Reason',
            field=models.ForeignKey(blank=True, default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='dashboard.PledgeItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledges',
            name='is_church_member',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=100),
        ),
    ]
