# Generated by Django 2.2.8 on 2020-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_auto_20200704_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='First_Name',
            field=models.CharField(default='good', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Second_Name',
            field=models.CharField(default='goodq', max_length=100),
            preserve_default=False,
        ),
    ]
