# Generated by Django 2.2.8 on 2020-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20200704_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='salariespaid',
            name='Archived_Status',
            field=models.CharField(blank=True, choices=[('ARCHIVED', 'ARCHIVED'), ('NOT-ARCHIVED', 'NOT-ARCHIVED')], default='NOT-ARCHIVED', max_length=1000, null=True),
        ),
    ]
