# Generated by Django 2.2.8 on 2020-07-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_salariespaid_archived_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalariesPaidReportArchive',
        ),
    ]
