# Generated by Django 2.2.8 on 2020-07-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0112_delete_salariespaidreportarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(max_length=10000, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='archivedmembers',
            name='Photo',
            field=models.ImageField(max_length=10000, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='church',
            name='Church_Logo',
            field=models.ImageField(max_length=10000, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(max_length=10000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Photo',
            field=models.ImageField(max_length=10000, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='photos',
            field=models.ImageField(blank=True, max_length=10000, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='audio_file',
            field=models.FileField(blank=True, max_length=10000, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_image',
            field=models.ImageField(max_length=10000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(max_length=10000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(max_length=10000, null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Photo',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='Photo',
            field=models.ImageField(blank=True, max_length=10000, upload_to='avatars/'),
        ),
    ]
