# Generated by Django 2.2.8 on 2020-07-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_auto_20200705_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledges',
            name='AmountBeingPaid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pledges',
            name='DateOfPayment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
