# Generated by Django 2.2.8 on 2020-07-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_auto_20200721_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledges',
            name='NameOfPledgee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
