# Generated by Django 2.2.8 on 2020-08-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_auto_20200721_0305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedMembers',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-id'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-gallery_image']},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['First_Name']},
        ),
    ]
