# Generated by Django 2.2.8 on 2020-09-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0118_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estemated_budget', models.IntegerField(blank=True, default=0, null=True)),
                ('conference_theme', models.CharField(blank=True, max_length=500, null=True)),
                ('conference_report', models.TextField(blank=True, max_length=100000, null=True)),
            ],
        ),
    ]
