# Generated by Django 2.2.8 on 2020-09-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_annualconference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualconference',
            old_name='estemated_budget',
            new_name='estimated_budget',
        ),
    ]
