# Generated by Django 2.2.8 on 2020-09-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0120_auto_20200911_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_church_member', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True)),
                ('born_again_before', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Second_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Telephone', models.CharField(max_length=100, null=True)),
                ('Date_Of_Salvation', models.DateField(blank=True, null=True)),
                ('member_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Members')),
            ],
        ),
    ]
