# Generated by Django 2.2.8 on 2020-09-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_newconvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newconvert',
            name='Telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
