# Generated by Django 2.2.8 on 2020-09-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_auto_20200915_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='core_values',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
    ]
