# Generated by Django 2.2.8 on 2020-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_about_core_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='church_details',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='about/'),
        ),
    ]
