# Generated by Django 2.2.8 on 2020-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0125_auto_20200928_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salariespaid',
            name='Month_being_cleared',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Month_being_cleared',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
