# Generated by Django 2.2.8 on 2020-10-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_about_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
