# Generated by Django 2.2.8 on 2020-10-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0131_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='First_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Photo',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Second_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='Telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
