# Generated by Django 2.2.8 on 2021-05-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('domain',),
            },
        ),
        migrations.CreateModel(
            name='XtdComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments.Comment')),
                ('thread_id', models.IntegerField(db_index=True, default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('level', models.SmallIntegerField(default=0)),
                ('order', models.IntegerField(db_index=True, default=1)),
                ('nested_count', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('submit_date',),
                'permissions': [('can_moderate', 'Can moderate comments')],
                'abstract': False,
            },
            bases=('django_comments.comment',),
        ),
    ]
