# Generated by Django 2.2.8 on 2021-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaginstance',
            name='reason',
            field=models.SmallIntegerField(choices=[(1, 'Spam | Exists only to promote a service'), (2, 'Abusive | Intended at promoting hatred'), (3, 'Racist | Sick mentality'), (4, 'Whatever | Your reason'), (100, 'Something else')], default=1),
        ),
    ]
